// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kusduxuxxaqtddhjnclj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1c2R1eHV4eGFxdGRkaGpuY2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzk2MjMsImV4cCI6MjA3MDc1NTYyM30.cSWs-vS8k4IrohSuS3eTh5RYere1_AGtWb5YRy0KQHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});